name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
        python: [3.11]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: pnpm
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: |
        corepack enable
        pnpm install --frozen-lockfile || true
        pip install -r requirements.txt
    - run: pnpm lint
    - run: pnpm test && pytest
    - run: pnpm build
